apiVersion: v1
kind: Service
metadata:
  name: pbs-operator-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: pbs-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: pbs-operator
