apiVersion: v1
kind: ServiceAccount
metadata:
  name: pbs-operator-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pbs-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
