---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - pbs.sharifmind.ir
  resources:
  - pbsbackups
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pbs.sharifmind.ir
  resources:
  - pbsbackups/status
  - pbsrepos/status
  - pbsrestores/status
  - pbsschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pbs.sharifmind.ir
  resources:
  - pbsrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pbs.sharifmind.ir
  resources:
  - pbsrestores
  - pbsschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pbs.sharifmind.ir
  resources:
  - pbsrestores/finalizers
  - pbsschedules/finalizers
  verbs:
  - update
