apiVersion: pbs.sharifmind.ir/v1
kind: PBSBackup
metadata:
  labels:
    app.kubernetes.io/name: pbs-operator
    app.kubernetes.io/managed-by: kustomize
  name: pbsbackup-sample
spec:
  repoRef: pbsrepo-sample
  # PVC selection: pvcs wins if set; else selector; else all PVCs in this namespace.
  pvcs:
    - pvc-sample
  # selector:
  #   matchLabels:
  #     backup: pbs
