apiVersion: pbs.pbs.sharifmind.ir/v1
kind: PBSSchedule
metadata:
  labels:
    app.kubernetes.io/name: pbs-operator
    app.kubernetes.io/managed-by: kustomize
  name: pbsschedule-sample
spec:
  # TODO(user): Add fields here
